// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage.proto

#ifndef PROTOBUF_INCLUDED_storage_2eproto
#define PROTOBUF_INCLUDED_storage_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_storage_2eproto 

namespace protobuf_storage_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[10];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_storage_2eproto
namespace kvstore {
class GetPageReply;
class GetPageReplyDefaultTypeInternal;
extern GetPageReplyDefaultTypeInternal _GetPageReply_default_instance_;
class GetPageRequest;
class GetPageRequestDefaultTypeInternal;
extern GetPageRequestDefaultTypeInternal _GetPageRequest_default_instance_;
class HelloReply;
class HelloReplyDefaultTypeInternal;
extern HelloReplyDefaultTypeInternal _HelloReply_default_instance_;
class HelloRequest;
class HelloRequestDefaultTypeInternal;
extern HelloRequestDefaultTypeInternal _HelloRequest_default_instance_;
class Item;
class ItemDefaultTypeInternal;
extern ItemDefaultTypeInternal _Item_default_instance_;
class LogEntry;
class LogEntryDefaultTypeInternal;
extern LogEntryDefaultTypeInternal _LogEntry_default_instance_;
class LogReplayReply;
class LogReplayReplyDefaultTypeInternal;
extern LogReplayReplyDefaultTypeInternal _LogReplayReply_default_instance_;
class LogReplayRequest;
class LogReplayRequestDefaultTypeInternal;
extern LogReplayRequestDefaultTypeInternal _LogReplayRequest_default_instance_;
class ShutdownReply;
class ShutdownReplyDefaultTypeInternal;
extern ShutdownReplyDefaultTypeInternal _ShutdownReply_default_instance_;
class ShutdownRequest;
class ShutdownRequestDefaultTypeInternal;
extern ShutdownRequestDefaultTypeInternal _ShutdownRequest_default_instance_;
}  // namespace kvstore
namespace google {
namespace protobuf {
template<> ::kvstore::GetPageReply* Arena::CreateMaybeMessage<::kvstore::GetPageReply>(Arena*);
template<> ::kvstore::GetPageRequest* Arena::CreateMaybeMessage<::kvstore::GetPageRequest>(Arena*);
template<> ::kvstore::HelloReply* Arena::CreateMaybeMessage<::kvstore::HelloReply>(Arena*);
template<> ::kvstore::HelloRequest* Arena::CreateMaybeMessage<::kvstore::HelloRequest>(Arena*);
template<> ::kvstore::Item* Arena::CreateMaybeMessage<::kvstore::Item>(Arena*);
template<> ::kvstore::LogEntry* Arena::CreateMaybeMessage<::kvstore::LogEntry>(Arena*);
template<> ::kvstore::LogReplayReply* Arena::CreateMaybeMessage<::kvstore::LogReplayReply>(Arena*);
template<> ::kvstore::LogReplayRequest* Arena::CreateMaybeMessage<::kvstore::LogReplayRequest>(Arena*);
template<> ::kvstore::ShutdownReply* Arena::CreateMaybeMessage<::kvstore::ShutdownReply>(Arena*);
template<> ::kvstore::ShutdownRequest* Arena::CreateMaybeMessage<::kvstore::ShutdownRequest>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace kvstore {

// ===================================================================

class HelloRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:kvstore.HelloRequest) */ {
 public:
  HelloRequest();
  virtual ~HelloRequest();

  HelloRequest(const HelloRequest& from);

  inline HelloRequest& operator=(const HelloRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  HelloRequest(HelloRequest&& from) noexcept
    : HelloRequest() {
    *this = ::std::move(from);
  }

  inline HelloRequest& operator=(HelloRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const HelloRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const HelloRequest* internal_default_instance() {
    return reinterpret_cast<const HelloRequest*>(
               &_HelloRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(HelloRequest* other);
  friend void swap(HelloRequest& a, HelloRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline HelloRequest* New() const final {
    return CreateMaybeMessage<HelloRequest>(NULL);
  }

  HelloRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<HelloRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const HelloRequest& from);
  void MergeFrom(const HelloRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(HelloRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // @@protoc_insertion_point(class_scope:kvstore.HelloRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_storage_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class HelloReply : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:kvstore.HelloReply) */ {
 public:
  HelloReply();
  virtual ~HelloReply();

  HelloReply(const HelloReply& from);

  inline HelloReply& operator=(const HelloReply& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  HelloReply(HelloReply&& from) noexcept
    : HelloReply() {
    *this = ::std::move(from);
  }

  inline HelloReply& operator=(HelloReply&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const HelloReply& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const HelloReply* internal_default_instance() {
    return reinterpret_cast<const HelloReply*>(
               &_HelloReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(HelloReply* other);
  friend void swap(HelloReply& a, HelloReply& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline HelloReply* New() const final {
    return CreateMaybeMessage<HelloReply>(NULL);
  }

  HelloReply* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<HelloReply>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const HelloReply& from);
  void MergeFrom(const HelloReply& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(HelloReply* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string message = 1;
  void clear_message();
  static const int kMessageFieldNumber = 1;
  const ::std::string& message() const;
  void set_message(const ::std::string& value);
  #if LANG_CXX11
  void set_message(::std::string&& value);
  #endif
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  ::std::string* mutable_message();
  ::std::string* release_message();
  void set_allocated_message(::std::string* message);

  // @@protoc_insertion_point(class_scope:kvstore.HelloReply)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr message_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_storage_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Item : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:kvstore.Item) */ {
 public:
  Item();
  virtual ~Item();

  Item(const Item& from);

  inline Item& operator=(const Item& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Item(Item&& from) noexcept
    : Item() {
    *this = ::std::move(from);
  }

  inline Item& operator=(Item&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Item& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Item* internal_default_instance() {
    return reinterpret_cast<const Item*>(
               &_Item_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(Item* other);
  friend void swap(Item& a, Item& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Item* New() const final {
    return CreateMaybeMessage<Item>(NULL);
  }

  Item* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Item>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Item& from);
  void MergeFrom(const Item& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Item* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string key = 1;
  void clear_key();
  static const int kKeyFieldNumber = 1;
  const ::std::string& key() const;
  void set_key(const ::std::string& value);
  #if LANG_CXX11
  void set_key(::std::string&& value);
  #endif
  void set_key(const char* value);
  void set_key(const char* value, size_t size);
  ::std::string* mutable_key();
  ::std::string* release_key();
  void set_allocated_key(::std::string* key);

  // string value = 2;
  void clear_value();
  static const int kValueFieldNumber = 2;
  const ::std::string& value() const;
  void set_value(const ::std::string& value);
  #if LANG_CXX11
  void set_value(::std::string&& value);
  #endif
  void set_value(const char* value);
  void set_value(const char* value, size_t size);
  ::std::string* mutable_value();
  ::std::string* release_value();
  void set_allocated_value(::std::string* value);

  // @@protoc_insertion_point(class_scope:kvstore.Item)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr key_;
  ::google::protobuf::internal::ArenaStringPtr value_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_storage_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GetPageRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:kvstore.GetPageRequest) */ {
 public:
  GetPageRequest();
  virtual ~GetPageRequest();

  GetPageRequest(const GetPageRequest& from);

  inline GetPageRequest& operator=(const GetPageRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GetPageRequest(GetPageRequest&& from) noexcept
    : GetPageRequest() {
    *this = ::std::move(from);
  }

  inline GetPageRequest& operator=(GetPageRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GetPageRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GetPageRequest* internal_default_instance() {
    return reinterpret_cast<const GetPageRequest*>(
               &_GetPageRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(GetPageRequest* other);
  friend void swap(GetPageRequest& a, GetPageRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GetPageRequest* New() const final {
    return CreateMaybeMessage<GetPageRequest>(NULL);
  }

  GetPageRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GetPageRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GetPageRequest& from);
  void MergeFrom(const GetPageRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetPageRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string page_id = 1;
  void clear_page_id();
  static const int kPageIdFieldNumber = 1;
  const ::std::string& page_id() const;
  void set_page_id(const ::std::string& value);
  #if LANG_CXX11
  void set_page_id(::std::string&& value);
  #endif
  void set_page_id(const char* value);
  void set_page_id(const char* value, size_t size);
  ::std::string* mutable_page_id();
  ::std::string* release_page_id();
  void set_allocated_page_id(::std::string* page_id);

  // @@protoc_insertion_point(class_scope:kvstore.GetPageRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr page_id_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_storage_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GetPageReply : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:kvstore.GetPageReply) */ {
 public:
  GetPageReply();
  virtual ~GetPageReply();

  GetPageReply(const GetPageReply& from);

  inline GetPageReply& operator=(const GetPageReply& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GetPageReply(GetPageReply&& from) noexcept
    : GetPageReply() {
    *this = ::std::move(from);
  }

  inline GetPageReply& operator=(GetPageReply&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GetPageReply& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GetPageReply* internal_default_instance() {
    return reinterpret_cast<const GetPageReply*>(
               &_GetPageReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(GetPageReply* other);
  friend void swap(GetPageReply& a, GetPageReply& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GetPageReply* New() const final {
    return CreateMaybeMessage<GetPageReply>(NULL);
  }

  GetPageReply* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GetPageReply>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GetPageReply& from);
  void MergeFrom(const GetPageReply& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetPageReply* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .kvstore.Item dataitem = 1;
  int dataitem_size() const;
  void clear_dataitem();
  static const int kDataitemFieldNumber = 1;
  ::kvstore::Item* mutable_dataitem(int index);
  ::google::protobuf::RepeatedPtrField< ::kvstore::Item >*
      mutable_dataitem();
  const ::kvstore::Item& dataitem(int index) const;
  ::kvstore::Item* add_dataitem();
  const ::google::protobuf::RepeatedPtrField< ::kvstore::Item >&
      dataitem() const;

  // @@protoc_insertion_point(class_scope:kvstore.GetPageReply)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::kvstore::Item > dataitem_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_storage_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ShutdownRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:kvstore.ShutdownRequest) */ {
 public:
  ShutdownRequest();
  virtual ~ShutdownRequest();

  ShutdownRequest(const ShutdownRequest& from);

  inline ShutdownRequest& operator=(const ShutdownRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ShutdownRequest(ShutdownRequest&& from) noexcept
    : ShutdownRequest() {
    *this = ::std::move(from);
  }

  inline ShutdownRequest& operator=(ShutdownRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ShutdownRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ShutdownRequest* internal_default_instance() {
    return reinterpret_cast<const ShutdownRequest*>(
               &_ShutdownRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(ShutdownRequest* other);
  friend void swap(ShutdownRequest& a, ShutdownRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ShutdownRequest* New() const final {
    return CreateMaybeMessage<ShutdownRequest>(NULL);
  }

  ShutdownRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ShutdownRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ShutdownRequest& from);
  void MergeFrom(const ShutdownRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ShutdownRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string signal = 1;
  void clear_signal();
  static const int kSignalFieldNumber = 1;
  const ::std::string& signal() const;
  void set_signal(const ::std::string& value);
  #if LANG_CXX11
  void set_signal(::std::string&& value);
  #endif
  void set_signal(const char* value);
  void set_signal(const char* value, size_t size);
  ::std::string* mutable_signal();
  ::std::string* release_signal();
  void set_allocated_signal(::std::string* signal);

  // @@protoc_insertion_point(class_scope:kvstore.ShutdownRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr signal_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_storage_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ShutdownReply : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:kvstore.ShutdownReply) */ {
 public:
  ShutdownReply();
  virtual ~ShutdownReply();

  ShutdownReply(const ShutdownReply& from);

  inline ShutdownReply& operator=(const ShutdownReply& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ShutdownReply(ShutdownReply&& from) noexcept
    : ShutdownReply() {
    *this = ::std::move(from);
  }

  inline ShutdownReply& operator=(ShutdownReply&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ShutdownReply& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ShutdownReply* internal_default_instance() {
    return reinterpret_cast<const ShutdownReply*>(
               &_ShutdownReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  void Swap(ShutdownReply* other);
  friend void swap(ShutdownReply& a, ShutdownReply& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ShutdownReply* New() const final {
    return CreateMaybeMessage<ShutdownReply>(NULL);
  }

  ShutdownReply* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ShutdownReply>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ShutdownReply& from);
  void MergeFrom(const ShutdownReply& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ShutdownReply* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string signalret = 1;
  void clear_signalret();
  static const int kSignalretFieldNumber = 1;
  const ::std::string& signalret() const;
  void set_signalret(const ::std::string& value);
  #if LANG_CXX11
  void set_signalret(::std::string&& value);
  #endif
  void set_signalret(const char* value);
  void set_signalret(const char* value, size_t size);
  ::std::string* mutable_signalret();
  ::std::string* release_signalret();
  void set_allocated_signalret(::std::string* signalret);

  // @@protoc_insertion_point(class_scope:kvstore.ShutdownReply)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr signalret_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_storage_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class LogEntry : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:kvstore.LogEntry) */ {
 public:
  LogEntry();
  virtual ~LogEntry();

  LogEntry(const LogEntry& from);

  inline LogEntry& operator=(const LogEntry& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  LogEntry(LogEntry&& from) noexcept
    : LogEntry() {
    *this = ::std::move(from);
  }

  inline LogEntry& operator=(LogEntry&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const LogEntry& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LogEntry* internal_default_instance() {
    return reinterpret_cast<const LogEntry*>(
               &_LogEntry_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  void Swap(LogEntry* other);
  friend void swap(LogEntry& a, LogEntry& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline LogEntry* New() const final {
    return CreateMaybeMessage<LogEntry>(NULL);
  }

  LogEntry* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<LogEntry>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const LogEntry& from);
  void MergeFrom(const LogEntry& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LogEntry* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes data = 1;
  void clear_data();
  static const int kDataFieldNumber = 1;
  const ::std::string& data() const;
  void set_data(const ::std::string& value);
  #if LANG_CXX11
  void set_data(::std::string&& value);
  #endif
  void set_data(const char* value);
  void set_data(const void* value, size_t size);
  ::std::string* mutable_data();
  ::std::string* release_data();
  void set_allocated_data(::std::string* data);

  // int32 size = 2;
  void clear_size();
  static const int kSizeFieldNumber = 2;
  ::google::protobuf::int32 size() const;
  void set_size(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:kvstore.LogEntry)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr data_;
  ::google::protobuf::int32 size_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_storage_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class LogReplayRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:kvstore.LogReplayRequest) */ {
 public:
  LogReplayRequest();
  virtual ~LogReplayRequest();

  LogReplayRequest(const LogReplayRequest& from);

  inline LogReplayRequest& operator=(const LogReplayRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  LogReplayRequest(LogReplayRequest&& from) noexcept
    : LogReplayRequest() {
    *this = ::std::move(from);
  }

  inline LogReplayRequest& operator=(LogReplayRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const LogReplayRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LogReplayRequest* internal_default_instance() {
    return reinterpret_cast<const LogReplayRequest*>(
               &_LogReplayRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  void Swap(LogReplayRequest* other);
  friend void swap(LogReplayRequest& a, LogReplayRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline LogReplayRequest* New() const final {
    return CreateMaybeMessage<LogReplayRequest>(NULL);
  }

  LogReplayRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<LogReplayRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const LogReplayRequest& from);
  void MergeFrom(const LogReplayRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LogReplayRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .kvstore.LogEntry entry = 1;
  int entry_size() const;
  void clear_entry();
  static const int kEntryFieldNumber = 1;
  ::kvstore::LogEntry* mutable_entry(int index);
  ::google::protobuf::RepeatedPtrField< ::kvstore::LogEntry >*
      mutable_entry();
  const ::kvstore::LogEntry& entry(int index) const;
  ::kvstore::LogEntry* add_entry();
  const ::google::protobuf::RepeatedPtrField< ::kvstore::LogEntry >&
      entry() const;

  // @@protoc_insertion_point(class_scope:kvstore.LogReplayRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::kvstore::LogEntry > entry_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_storage_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class LogReplayReply : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:kvstore.LogReplayReply) */ {
 public:
  LogReplayReply();
  virtual ~LogReplayReply();

  LogReplayReply(const LogReplayReply& from);

  inline LogReplayReply& operator=(const LogReplayReply& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  LogReplayReply(LogReplayReply&& from) noexcept
    : LogReplayReply() {
    *this = ::std::move(from);
  }

  inline LogReplayReply& operator=(LogReplayReply&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const LogReplayReply& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LogReplayReply* internal_default_instance() {
    return reinterpret_cast<const LogReplayReply*>(
               &_LogReplayReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    9;

  void Swap(LogReplayReply* other);
  friend void swap(LogReplayReply& a, LogReplayReply& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline LogReplayReply* New() const final {
    return CreateMaybeMessage<LogReplayReply>(NULL);
  }

  LogReplayReply* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<LogReplayReply>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const LogReplayReply& from);
  void MergeFrom(const LogReplayReply& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LogReplayReply* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 numreplay = 1;
  void clear_numreplay();
  static const int kNumreplayFieldNumber = 1;
  ::google::protobuf::int32 numreplay() const;
  void set_numreplay(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:kvstore.LogReplayReply)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 numreplay_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_storage_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// HelloRequest

// string name = 1;
inline void HelloRequest::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& HelloRequest::name() const {
  // @@protoc_insertion_point(field_get:kvstore.HelloRequest.name)
  return name_.GetNoArena();
}
inline void HelloRequest::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:kvstore.HelloRequest.name)
}
#if LANG_CXX11
inline void HelloRequest::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:kvstore.HelloRequest.name)
}
#endif
inline void HelloRequest::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:kvstore.HelloRequest.name)
}
inline void HelloRequest::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:kvstore.HelloRequest.name)
}
inline ::std::string* HelloRequest::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:kvstore.HelloRequest.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* HelloRequest::release_name() {
  // @@protoc_insertion_point(field_release:kvstore.HelloRequest.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void HelloRequest::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:kvstore.HelloRequest.name)
}

// -------------------------------------------------------------------

// HelloReply

// string message = 1;
inline void HelloReply::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& HelloReply::message() const {
  // @@protoc_insertion_point(field_get:kvstore.HelloReply.message)
  return message_.GetNoArena();
}
inline void HelloReply::set_message(const ::std::string& value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:kvstore.HelloReply.message)
}
#if LANG_CXX11
inline void HelloReply::set_message(::std::string&& value) {
  
  message_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:kvstore.HelloReply.message)
}
#endif
inline void HelloReply::set_message(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:kvstore.HelloReply.message)
}
inline void HelloReply::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:kvstore.HelloReply.message)
}
inline ::std::string* HelloReply::mutable_message() {
  
  // @@protoc_insertion_point(field_mutable:kvstore.HelloReply.message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* HelloReply::release_message() {
  // @@protoc_insertion_point(field_release:kvstore.HelloReply.message)
  
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void HelloReply::set_allocated_message(::std::string* message) {
  if (message != NULL) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:kvstore.HelloReply.message)
}

// -------------------------------------------------------------------

// Item

// string key = 1;
inline void Item::clear_key() {
  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Item::key() const {
  // @@protoc_insertion_point(field_get:kvstore.Item.key)
  return key_.GetNoArena();
}
inline void Item::set_key(const ::std::string& value) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:kvstore.Item.key)
}
#if LANG_CXX11
inline void Item::set_key(::std::string&& value) {
  
  key_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:kvstore.Item.key)
}
#endif
inline void Item::set_key(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:kvstore.Item.key)
}
inline void Item::set_key(const char* value, size_t size) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:kvstore.Item.key)
}
inline ::std::string* Item::mutable_key() {
  
  // @@protoc_insertion_point(field_mutable:kvstore.Item.key)
  return key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Item::release_key() {
  // @@protoc_insertion_point(field_release:kvstore.Item.key)
  
  return key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Item::set_allocated_key(::std::string* key) {
  if (key != NULL) {
    
  } else {
    
  }
  key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), key);
  // @@protoc_insertion_point(field_set_allocated:kvstore.Item.key)
}

// string value = 2;
inline void Item::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Item::value() const {
  // @@protoc_insertion_point(field_get:kvstore.Item.value)
  return value_.GetNoArena();
}
inline void Item::set_value(const ::std::string& value) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:kvstore.Item.value)
}
#if LANG_CXX11
inline void Item::set_value(::std::string&& value) {
  
  value_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:kvstore.Item.value)
}
#endif
inline void Item::set_value(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:kvstore.Item.value)
}
inline void Item::set_value(const char* value, size_t size) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:kvstore.Item.value)
}
inline ::std::string* Item::mutable_value() {
  
  // @@protoc_insertion_point(field_mutable:kvstore.Item.value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Item::release_value() {
  // @@protoc_insertion_point(field_release:kvstore.Item.value)
  
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Item::set_allocated_value(::std::string* value) {
  if (value != NULL) {
    
  } else {
    
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:kvstore.Item.value)
}

// -------------------------------------------------------------------

// GetPageRequest

// string page_id = 1;
inline void GetPageRequest::clear_page_id() {
  page_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GetPageRequest::page_id() const {
  // @@protoc_insertion_point(field_get:kvstore.GetPageRequest.page_id)
  return page_id_.GetNoArena();
}
inline void GetPageRequest::set_page_id(const ::std::string& value) {
  
  page_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:kvstore.GetPageRequest.page_id)
}
#if LANG_CXX11
inline void GetPageRequest::set_page_id(::std::string&& value) {
  
  page_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:kvstore.GetPageRequest.page_id)
}
#endif
inline void GetPageRequest::set_page_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  page_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:kvstore.GetPageRequest.page_id)
}
inline void GetPageRequest::set_page_id(const char* value, size_t size) {
  
  page_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:kvstore.GetPageRequest.page_id)
}
inline ::std::string* GetPageRequest::mutable_page_id() {
  
  // @@protoc_insertion_point(field_mutable:kvstore.GetPageRequest.page_id)
  return page_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GetPageRequest::release_page_id() {
  // @@protoc_insertion_point(field_release:kvstore.GetPageRequest.page_id)
  
  return page_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GetPageRequest::set_allocated_page_id(::std::string* page_id) {
  if (page_id != NULL) {
    
  } else {
    
  }
  page_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), page_id);
  // @@protoc_insertion_point(field_set_allocated:kvstore.GetPageRequest.page_id)
}

// -------------------------------------------------------------------

// GetPageReply

// repeated .kvstore.Item dataitem = 1;
inline int GetPageReply::dataitem_size() const {
  return dataitem_.size();
}
inline void GetPageReply::clear_dataitem() {
  dataitem_.Clear();
}
inline ::kvstore::Item* GetPageReply::mutable_dataitem(int index) {
  // @@protoc_insertion_point(field_mutable:kvstore.GetPageReply.dataitem)
  return dataitem_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::kvstore::Item >*
GetPageReply::mutable_dataitem() {
  // @@protoc_insertion_point(field_mutable_list:kvstore.GetPageReply.dataitem)
  return &dataitem_;
}
inline const ::kvstore::Item& GetPageReply::dataitem(int index) const {
  // @@protoc_insertion_point(field_get:kvstore.GetPageReply.dataitem)
  return dataitem_.Get(index);
}
inline ::kvstore::Item* GetPageReply::add_dataitem() {
  // @@protoc_insertion_point(field_add:kvstore.GetPageReply.dataitem)
  return dataitem_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::kvstore::Item >&
GetPageReply::dataitem() const {
  // @@protoc_insertion_point(field_list:kvstore.GetPageReply.dataitem)
  return dataitem_;
}

// -------------------------------------------------------------------

// ShutdownRequest

// string signal = 1;
inline void ShutdownRequest::clear_signal() {
  signal_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ShutdownRequest::signal() const {
  // @@protoc_insertion_point(field_get:kvstore.ShutdownRequest.signal)
  return signal_.GetNoArena();
}
inline void ShutdownRequest::set_signal(const ::std::string& value) {
  
  signal_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:kvstore.ShutdownRequest.signal)
}
#if LANG_CXX11
inline void ShutdownRequest::set_signal(::std::string&& value) {
  
  signal_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:kvstore.ShutdownRequest.signal)
}
#endif
inline void ShutdownRequest::set_signal(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  signal_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:kvstore.ShutdownRequest.signal)
}
inline void ShutdownRequest::set_signal(const char* value, size_t size) {
  
  signal_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:kvstore.ShutdownRequest.signal)
}
inline ::std::string* ShutdownRequest::mutable_signal() {
  
  // @@protoc_insertion_point(field_mutable:kvstore.ShutdownRequest.signal)
  return signal_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ShutdownRequest::release_signal() {
  // @@protoc_insertion_point(field_release:kvstore.ShutdownRequest.signal)
  
  return signal_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ShutdownRequest::set_allocated_signal(::std::string* signal) {
  if (signal != NULL) {
    
  } else {
    
  }
  signal_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), signal);
  // @@protoc_insertion_point(field_set_allocated:kvstore.ShutdownRequest.signal)
}

// -------------------------------------------------------------------

// ShutdownReply

// string signalret = 1;
inline void ShutdownReply::clear_signalret() {
  signalret_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ShutdownReply::signalret() const {
  // @@protoc_insertion_point(field_get:kvstore.ShutdownReply.signalret)
  return signalret_.GetNoArena();
}
inline void ShutdownReply::set_signalret(const ::std::string& value) {
  
  signalret_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:kvstore.ShutdownReply.signalret)
}
#if LANG_CXX11
inline void ShutdownReply::set_signalret(::std::string&& value) {
  
  signalret_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:kvstore.ShutdownReply.signalret)
}
#endif
inline void ShutdownReply::set_signalret(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  signalret_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:kvstore.ShutdownReply.signalret)
}
inline void ShutdownReply::set_signalret(const char* value, size_t size) {
  
  signalret_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:kvstore.ShutdownReply.signalret)
}
inline ::std::string* ShutdownReply::mutable_signalret() {
  
  // @@protoc_insertion_point(field_mutable:kvstore.ShutdownReply.signalret)
  return signalret_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ShutdownReply::release_signalret() {
  // @@protoc_insertion_point(field_release:kvstore.ShutdownReply.signalret)
  
  return signalret_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ShutdownReply::set_allocated_signalret(::std::string* signalret) {
  if (signalret != NULL) {
    
  } else {
    
  }
  signalret_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), signalret);
  // @@protoc_insertion_point(field_set_allocated:kvstore.ShutdownReply.signalret)
}

// -------------------------------------------------------------------

// LogEntry

// bytes data = 1;
inline void LogEntry::clear_data() {
  data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& LogEntry::data() const {
  // @@protoc_insertion_point(field_get:kvstore.LogEntry.data)
  return data_.GetNoArena();
}
inline void LogEntry::set_data(const ::std::string& value) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:kvstore.LogEntry.data)
}
#if LANG_CXX11
inline void LogEntry::set_data(::std::string&& value) {
  
  data_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:kvstore.LogEntry.data)
}
#endif
inline void LogEntry::set_data(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:kvstore.LogEntry.data)
}
inline void LogEntry::set_data(const void* value, size_t size) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:kvstore.LogEntry.data)
}
inline ::std::string* LogEntry::mutable_data() {
  
  // @@protoc_insertion_point(field_mutable:kvstore.LogEntry.data)
  return data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LogEntry::release_data() {
  // @@protoc_insertion_point(field_release:kvstore.LogEntry.data)
  
  return data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LogEntry::set_allocated_data(::std::string* data) {
  if (data != NULL) {
    
  } else {
    
  }
  data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), data);
  // @@protoc_insertion_point(field_set_allocated:kvstore.LogEntry.data)
}

// int32 size = 2;
inline void LogEntry::clear_size() {
  size_ = 0;
}
inline ::google::protobuf::int32 LogEntry::size() const {
  // @@protoc_insertion_point(field_get:kvstore.LogEntry.size)
  return size_;
}
inline void LogEntry::set_size(::google::protobuf::int32 value) {
  
  size_ = value;
  // @@protoc_insertion_point(field_set:kvstore.LogEntry.size)
}

// -------------------------------------------------------------------

// LogReplayRequest

// repeated .kvstore.LogEntry entry = 1;
inline int LogReplayRequest::entry_size() const {
  return entry_.size();
}
inline void LogReplayRequest::clear_entry() {
  entry_.Clear();
}
inline ::kvstore::LogEntry* LogReplayRequest::mutable_entry(int index) {
  // @@protoc_insertion_point(field_mutable:kvstore.LogReplayRequest.entry)
  return entry_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::kvstore::LogEntry >*
LogReplayRequest::mutable_entry() {
  // @@protoc_insertion_point(field_mutable_list:kvstore.LogReplayRequest.entry)
  return &entry_;
}
inline const ::kvstore::LogEntry& LogReplayRequest::entry(int index) const {
  // @@protoc_insertion_point(field_get:kvstore.LogReplayRequest.entry)
  return entry_.Get(index);
}
inline ::kvstore::LogEntry* LogReplayRequest::add_entry() {
  // @@protoc_insertion_point(field_add:kvstore.LogReplayRequest.entry)
  return entry_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::kvstore::LogEntry >&
LogReplayRequest::entry() const {
  // @@protoc_insertion_point(field_list:kvstore.LogReplayRequest.entry)
  return entry_;
}

// -------------------------------------------------------------------

// LogReplayReply

// int32 numreplay = 1;
inline void LogReplayReply::clear_numreplay() {
  numreplay_ = 0;
}
inline ::google::protobuf::int32 LogReplayReply::numreplay() const {
  // @@protoc_insertion_point(field_get:kvstore.LogReplayReply.numreplay)
  return numreplay_;
}
inline void LogReplayReply::set_numreplay(::google::protobuf::int32 value) {
  
  numreplay_ = value;
  // @@protoc_insertion_point(field_set:kvstore.LogReplayReply.numreplay)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace kvstore

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_storage_2eproto
