syntax = "proto3";

option java_multiple_files = true;
option java_package = "io.grpc.storage.kvstore";
option java_outer_classname = "StoreageProto";
option objc_class_prefix = "KVSTORE";

package kvstore;

// The greeting service definition.
service Greeter {
  // Sends a greeting
  rpc SayHello (HelloRequest) returns (HelloReply) {}
}

// The request message containing the user's name.
message HelloRequest {
  string name = 1;
}

// The response message containing the greetings
message HelloReply {
  string message = 1;
}

service PageLoader {
  // Sends a greeting
  rpc GetPage (GetPageRequest) returns (GetPageReply) {}
  rpc ShutdownServer (ShutdownRequest) returns (ShutdownReply) {}
}

message GetPageRequest {
  string page_id = 1;
}

message Item {
  string key = 1;
  string value = 2;
}

message GetPageReply {
  repeated Item dataitem = 1;
}

message ShutdownRequest {
  string signal = 1;
}

message ShutdownReply {
  string signalret = 1;
}