PROJECT_ROOT ?= $(shell readlink -f .)


CC=g++
CFLAGS=-Wall -g -std=c++0x -no-pie

.SUFFIXES: .o .cpp .h

SRC_DIRS = ./ ./common/ ./untrusted/system/ ./untrusted/benchmarks/ ./untrusted/cache/ ./trusted/system/ ./trusted/concurrency_control/
INCLUDE = -I. -I./common/ -I./untrusted/system/ -I./untrusted/benchmarks/ -I./untrusted/cache/ -I./trusted/system/ -I./trusted/concurrency_control/

# SRC_DIRS = ./ ./common ./untrusted/system/ ./untrusted/benchmarks/ ./untrusted/cache/
# INCLUDE = -I. -I./common -I./untrusted/system -I./untrusted/benchmarks/ -I./untrusted/cache/

# CFLAGS += $(INCLUDE) -D NOGRAPHITE=1 -no-pie -O0
# LDFLAGS = -Wall -L. -L./libs -pthread -g -lrt -std=c++0x -O0 -ljemalloc

CFLAGS += $(INCLUDE) -D NOGRAPHITE=1 -Werror -Wno-comment -O0
LDFLAGS = -Wall -L.  -L./libs -pthread -g -lrt -std=c++0x -O0 -ljemalloc -lnanomsg  -lrocksdb
# LDFLAGS = -Wall -L. -pthread -g -lrt -std=c++0x -O0 -ljemalloc -fsanitize=address -fno-omit-frame-pointer -static-libasan
LDFLAGS += $(CFLAGS)

CPPS = $(foreach dir, $(SRC_DIRS), $(wildcard $(dir)*.cpp))
OBJS = $(CPPS:.cpp=.o)
DEPS = $(CPPS:.cpp=.d)

all:rundb

rundb : $(OBJS)
	$(CC) -o $@ $^ $(LDFLAGS)

-include $(OBJS:%.o=%.d)

%.d: %.cpp
	$(CC) -MM -MT $*.o -MF $@ $(CFLAGS) $<

%.o: %.cpp
	$(CC) -c $(CFLAGS) -o $@ $<

.PHONY: clean
clean:
	rm -f rundb ./trusted/*.o ./trusted/*.d ./untrusted/*.o ./untrusted/*.d ./common/*.o ./common/*.d $(OBJS) $(DEPS)

# $(DEPS)


sgx-release:
	cp ./sgx_files/release/main.cpp ./main.cpp
	cp ./sgx_files/release/Makefile.sgx ./Makefile.sgx
	cp ./sgx_files/release/sgx_t.mk ./sgx_t.mk
	cp ./sgx_files/release/sgx_u.mk ./sgx_u.mk
	cp ./sgx_files/release/Enclave.config.xml ./trusted/Enclave.config.xml
	cp Makefile.sgx Makefile

sgx-debug:
	cp ./sgx_files/debug/main.cpp ./main.cpp
	cp ./sgx_files/debug/Makefile.sgx ./Makefile.sgx
	cp ./sgx_files/debug/sgx_t.mk ./sgx_t.mk
	cp ./sgx_files/debug/sgx_u.mk ./sgx_u.mk
	cp ./sgx_files/debug/Enclave.config.xml ./trusted/Enclave.config.xml
	cp Makefile.sgx Makefile
